location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mins
    name: mins
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mins_estimator_plugin
    name: mrs_mins_estimator_plugin
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_mins_estimator_plugin
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_vins_imu_filter
    name: mrs_vins_imu_filter
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_vins_imu_filter
    scripts:
      - git submodule update --init --recursive
