topics: # topics published out of this machine to receivers specified above
 # - name: "goal_transformer/goal_out"
 #   compress: true # enable bz2 compression
 #   rate: 20.0
 - name: "estimation_manager/odom_main"
   compress: true # enable bz2 compression
   rate: 2.0
 - name: "octomap_server/octomap_local_binary"
   compress: true # enable bz2 compression
   rate: 0.5
 - name: "octo_exploration/exploration_diag"
   compress: true # enable bz2 compression
   rate: 2.0
 # - name: "control_manager/mpc_tracker/diagnostics"
 #   compress: true # enable bz2 compression
 #   rate: 1.0
 # - name: "control_manager/diagnostics"
 #   compress: true # enable bz2 compression
 #   rate: 1.0
 # - name: "uav_manager/diagnostics"
 #   compress: true # enable bz2 compression
 #   rate: 1.0
 # - name: "control_manager/mpc_tracker/predicted_trajectory"
 #   compress: true # enable bz2 compression
 #   rate: 2.0
 # - name: "mrs_uav_status/uav_status"
 #   compress: true # enable bz2 compression
 #   rate: 1.0
 # - name: "mrs_uav_status/uav_status_short"
 #   compress: true # enable bz2 compression
 #   rate: 10.0

services:
  - name: "control_manager/stop_trajectory_tracking"
    type: std_srvs/Trigger
  - name: "control_manager/resume_trajectory_tracking"
    type: std_srvs/Trigger
  - name: "trajectory_generation/path"
    type: mrs_msgs/PathSrv
#   - name: "pathfinder/reference"
#     type: mrs_msgs/ReferenceStampedSrv
#   - name: "/*/control_manager/start_trajectory_tracking"
#     type: std_srvs/Trigger
#   - name: "/*/control_manager/trajectory_reference"
#     type: mrs_msgs/TrajectoryReferenceSrv
#   - name: "/*/uav_manager/land_home"
#     type: std_srvs/Trigger
#   - name: "/*/control_manager/switch_controller"
#     type: mrs_msgs/String
#   - name: "/*/control_manager/switch_tracker"
#     type: mrs_msgs/String
#   - name: "/*/constraint_manager/set_constraints"
#     type: mrs_msgs/String
#   - name: "/*/control_manager/enable_callbacks"
#     type: std_srvs/SetBool
#   - name: "/*/odometry/change_alt_estimator_type_string"
#     type: mrs_msgs/String
