%YAML:1.0 # need to specify the file type at the top!

cam:
  enabled: true
  time_analysis: false
  num_opencv_threads: 4 # -1: auto, 0-1: serial, >1: number of threads
  max_n: 1
  use_stereo: false
  stereo_pair: [0]
  do_calib_ext: true
  do_calib_int: true
  do_calib_dt: true
  n_pts: 200
  fast: 15
  grid_x: 10
  grid_y: 10
  min_px_dist: 20
  knn: 0.70
  downsample: false
  histogram_method: "HISTOGRAM" # NONE, HISTOGRAM, CLAHE
  max_slam: 50
  max_msckf: 50 # if there are more slam points than max_msckf, new ones are not initialized
  feat_rep: "GLOBAL_3D"
  init_cov_dt: 1e-4
  init_cov_ex_o: 1e-4
  init_cov_ex_p: 1e-3
  init_cov_in_k: 1e-0
  init_cov_in_c: 1e-0
  init_cov_in_r: 1e-5
  sigma_px: 1
  chi2_mult: 2.0
  fi_max_dist: 60.0 # [m] maximum distance to accept triangulated features


  # ==================================================================
  # ==================================================================
cam0:
  timeoffset:  0.033
  T_imu_cam:
    - [ 0.018, 0.013, 1.000, 0.057]
    - [-1.000, 0.002, 0.018, 0.033]
    - [-0.002,-1.000, 0.013, 0.043]
    - [ 0.000, 0.000, 0.000, 1.000]
  intrinsics: [216.48459,215.89565,381.46084,212.44569]
  distortion_coeffs: [-0.01743,0.00697,-0.00667,0.00067]
  resolution: [752, 480]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_model: equidistant
  topic: "bluefox_vio_front/image_raw"
  use_mask: true
  mask: "mask_mv_25003671.png"
