%YAML:1.0 # need to specify the file type at the top!

init:
  window_time: 2.0
  # imu_thresh: 1.0 # mavros imu
  imu_thresh: 0.2 # t265 imu
  imu_wheel_thresh: 0.05
  imu_only_init: true
  imu_gravity_aligned: false
  use_gt: false
  use_gt_gnss: false
  use_gt_lidar: false
  cov_size: 1e-4
