oak:
  diagnostic_updater:
    period: 1.0

  camera_i_calibration_dump: false
  camera_i_enable_imu: true
  camera_i_enable_ir: true
  camera_i_floodlight_brightness: 0
  camera_i_laser_dot_brightness: 0
  camera_i_nn_type: none
  camera_i_pipeline_dump: false
  camera_i_pipeline_type: Stereo
  camera_i_publish_tf_from_calibration: false
  camera_i_tf_base_frame: oak
  camera_i_tf_camera_name: oak
  camera_i_tf_imu_from_descr: 'false'
  camera_i_tf_parent_frame: oak-d-base-frame
  camera_i_usb_speed: SUPER_PLUS


  imu_i_acc_cov: 0.0
  imu_i_acc_freq: 200
  imu_i_batch_report_threshold: 0
  imu_i_enable_rotation: false
  imu_i_get_base_device_timestamp: false
  imu_i_gyro_cov: 0.0
  imu_i_gyro_freq: 200
  imu_i_mag_cov: 0.0
  imu_i_max_batch_reports: 10
  imu_i_message_type: IMU
  imu_i_rot_cov: -1.0
  imu_i_sync_method: LINEAR_INTERPOLATE_ACCEL
  imu_i_update_ros_base_time_on_ros_msg: false

  left_i_add_exposure_offset: false
  left_i_board_socket_id: 1
  left_i_calibration_file: ''
  left_i_disable_node: false
  left_i_enable_feature_tracker: false
  left_i_enable_lazy_publisher: true
  left_i_exposure_offset: 0
  left_i_fps: 30.0
  left_i_fsync_continuous: false
  left_i_fsync_trigger: false
  left_i_get_base_device_timestamp: false
  left_i_height: 720
  left_i_low_bandwidth: false
  left_i_low_bandwidth_quality: 50
  left_i_max_q_size: 2
  left_i_publish_topic: true
  left_i_resolution: '720P'
  left_i_reverse_stereo_socket_order: false
  left_i_sensor_img_orientation: NORMAL
  left_i_set_isp3a_fps: false
  left_i_simulate_from_topic: false
  left_i_simulated_topic_name: ''
  left_i_update_ros_base_time_on_ros_msg: false
  left_i_width: 1280
  left_r_exposure: 5000
  left_r_iso: 200
  left_r_set_man_exposure: false

  nn_i_disable_resize: false
  nn_i_enable_passthrough: false
  nn_i_enable_passthrough_depth: false
  nn_i_get_base_device_timestamp: false
  nn_i_num_inference_threads: 2
  nn_i_num_pool_frames: 4
  nn_i_update_ros_base_time_on_ros_msg: false

  rgb_i_add_exposure_offset: false
  rgb_i_board_socket_id: 0
  rgb_i_calibration_file: ''
  rgb_i_disable_node: true
  rgb_i_enable_feature_tracker: false
  rgb_i_enable_lazy_publisher: true
  rgb_i_enable_preview: false
  rgb_i_exposure_offset: 0
  rgb_i_fps: 30.0
  rgb_i_fsync_continuous: false
  rgb_i_fsync_trigger: false
  rgb_i_get_base_device_timestamp: false
  rgb_i_height: 720
  rgb_i_interleaved: false
  rgb_i_isp_den: 3
  rgb_i_isp_num: 2
  rgb_i_keep_preview_aspect_ratio: true
  rgb_i_low_bandwidth: false
  rgb_i_low_bandwidth_quality: 50
  rgb_i_max_q_size: 30
  rgb_i_output_isp: true
  rgb_i_preview_height: 300
  rgb_i_preview_size: 300
  rgb_i_preview_width: 300
  rgb_i_publish_topic: true
  rgb_i_resolution: 1080p
  rgb_i_reverse_stereo_socket_order: false
  rgb_i_sensor_img_orientation: NORMAL
  rgb_i_set_isp3a_fps: false
  rgb_i_set_isp_scale: true
  rgb_i_simulate_from_topic: false
  rgb_i_simulated_topic_name: ''
  rgb_i_update_ros_base_time_on_ros_msg: false
  rgb_i_width: 1280
  rgb_r_exposure: 20000
  rgb_r_focus: 1
  rgb_r_iso: 800
  rgb_r_set_man_exposure: false
  rgb_r_set_man_focus: false
  rgb_r_set_man_whitebalance: false
  rgb_r_whitebalance: 3300

  right_i_add_exposure_offset: false
  right_i_board_socket_id: 2
  right_i_calibration_file: ''
  right_i_disable_node: false
  right_i_enable_feature_tracker: false
  right_i_enable_lazy_publisher: true
  right_i_exposure_offset: 0
  right_i_fps: 30.0
  right_i_fsync_continuous: false
  right_i_fsync_trigger: false
  right_i_get_base_device_timestamp: false
  right_i_height: 720
  right_i_low_bandwidth: false
  right_i_low_bandwidth_quality: 50
  right_i_max_q_size: 2
  right_i_publish_topic: true
  right_i_resolution: '720P'
  right_i_reverse_stereo_socket_order: false
  right_i_sensor_img_orientation: NORMAL
  right_i_set_isp3a_fps: false
  right_i_simulate_from_topic: false
  right_i_simulated_topic_name: ''
  right_i_update_ros_base_time_on_ros_msg: false
  right_i_width: 1280
  right_r_exposure: 5000
  right_r_iso: 200
  right_r_set_man_exposure: false

  stereo_i_add_exposure_offset: false
  stereo_i_align_depth: false
  stereo_i_bilateral_sigma: 0
  stereo_i_board_socket_id: 0
  stereo_i_depth_filter_size: 5
  stereo_i_depth_preset: HIGH_ACCURACY
  stereo_i_disparity_width: DISPARITY_96
  stereo_i_enable_alpha_scaling: false
  stereo_i_enable_brightness_filter: false
  stereo_i_enable_companding: false
  stereo_i_enable_decimation_filter: false
  stereo_i_enable_disparity_shift: false
  stereo_i_enable_distortion_correction: false
  stereo_i_enable_lazy_publisher: true
  stereo_i_enable_spatial_filter: false
  stereo_i_enable_speckle_filter: false
  stereo_i_enable_temporal_filter: false
  stereo_i_enable_threshold_filter: false
  stereo_i_exposure_offset: 0
  stereo_i_extended_disp: false
  stereo_i_get_base_device_timestamp: false
  stereo_i_height: 720
  stereo_i_left_rect_add_exposure_offset: false
  stereo_i_left_rect_enable_feature_tracker: false
  stereo_i_left_rect_exposure_offset: 0
  stereo_i_left_rect_low_bandwidth: false
  stereo_i_left_rect_low_bandwidth_quality: 50
  stereo_i_left_socket_id: 1
  stereo_i_low_bandwidth: false
  stereo_i_low_bandwidth_quality: 50
  stereo_i_lr_check: true
  stereo_i_lrc_threshold: 10
  stereo_i_max_q_size: 30
  stereo_i_output_disparity: false
  stereo_i_publish_left_rect: false
  stereo_i_publish_right_rect: false
  stereo_i_publish_synced_rect_pair: false
  stereo_i_publish_topic: true
  stereo_i_rectify_edge_fill_color: 0
  stereo_i_reverse_stereo_socket_order: false
  stereo_i_right_rect_add_exposure_offset: false
  stereo_i_right_rect_enable_feature_tracker: false
  stereo_i_right_rect_exposure_offset: 0
  stereo_i_right_rect_low_bandwidth: false
  stereo_i_right_rect_low_bandwidth_quality: 50
  stereo_i_right_socket_id: 2
  stereo_i_set_input_size: false
  stereo_i_socket_name: rgb
  stereo_i_stereo_conf_threshold: 240
  stereo_i_subpixel: false
  stereo_i_update_ros_base_time_on_ros_msg: false
  stereo_i_width: 1280
